# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d214c16d6cf63333e000e0f21cb1758e2cfccea39720be09ee29027195909632160d91eb2949a8a691af1350dc3317ace8c2d1dab1c3d90b5e234f515a4fbe

test:
  secret_key_base: c9135d118c147e2079166cb8657890e08eb5f646dafa0faafd12d3cede0b22f902dc4df741491bb82c5eddcfe157d5afb74994a8cb8a9347ebf79f2fde35ee1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
